version: "3"
services:
  app:
    container_name: app
    build:
      context: ./golang
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CONTENT_STRING: "Hello There Friend"
    command: ./go_binary
    ports:
      - "9001:9001"
    networks:
      - backend

  redis:
    container_name: redis
    image: redis:latest
    networks:
      - backend

networks:
  backend:
